import {
  ROLE_AUDITOR,
  ROLE_CFO,
  ROLE_FINANCE_MANAGER,
  ROLE_MANAGER,
  ROLE_ORG_ADMIN,
  ROLE_SUPER_ADMIN,
  type SystemRoleSlug,
} from "@/lib/auth/constants";

export const SUPPLY_CHAIN_DASHBOARD_ROLES = [
  ROLE_SUPER_ADMIN,
  ROLE_ORG_ADMIN,
  ROLE_MANAGER,
  ROLE_CFO,
  ROLE_FINANCE_MANAGER,
  ROLE_AUDITOR,
] as const satisfies readonly SystemRoleSlug[];

export const INVENTORY_DASHBOARD_ROLES = SUPPLY_CHAIN_DASHBOARD_ROLES;
export const PRODUCTION_DASHBOARD_ROLES = SUPPLY_CHAIN_DASHBOARD_ROLES;
