import {
  ROLE_AUDITOR,
  ROLE_CFO,
  ROLE_FINANCE_MANAGER,
  ROLE_MANAGER,
  ROLE_ORG_ADMIN,
  ROLE_SUPER_ADMIN,
  type SystemRoleSlug,
} from "@/lib/auth/constants";

export const EXECUTIVE_DASHBOARD_ROLES = [
  ROLE_SUPER_ADMIN,
  ROLE_ORG_ADMIN,
  ROLE_MANAGER,
  ROLE_CFO,
  ROLE_FINANCE_MANAGER,
  ROLE_AUDITOR,
] as const satisfies readonly SystemRoleSlug[];

export const CEO_DASHBOARD_ROLES = EXECUTIVE_DASHBOARD_ROLES;
export const CFO_DASHBOARD_ROLES = EXECUTIVE_DASHBOARD_ROLES;
export const BOARD_MIS_ROLES = EXECUTIVE_DASHBOARD_ROLES;
